// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/blog" | "/blog/[slug]" | "/contacto" | "/control-accesos" | "/legal/aviso-legal" | "/legal/cookies" | "/legal/privacidad" | "/parkings" | "/productos/elysium" | "/productos/elysium-plus" | "/productos/evo" | "/productos/prometheus" | "/studio/[[...tool]]" | "/verifactu"
type AppRouteHandlerRoutes = "/api/contact" | "/api/ping-google"
type PageRoutes = never
type LayoutRoutes = "/" | "/blog" | "/control-accesos" | "/legal" | "/parkings" | "/studio/[[...tool]]" | "/verifactu"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/contact": {}
  "/api/ping-google": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/contacto": {}
  "/control-accesos": {}
  "/legal": {}
  "/legal/aviso-legal": {}
  "/legal/cookies": {}
  "/legal/privacidad": {}
  "/parkings": {}
  "/productos/elysium": {}
  "/productos/elysium-plus": {}
  "/productos/evo": {}
  "/productos/prometheus": {}
  "/studio/[[...tool]]": { "tool"?: string[]; }
  "/verifactu": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/blog": never
  "/control-accesos": never
  "/legal": never
  "/parkings": never
  "/studio/[[...tool]]": never
  "/verifactu": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
