// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../../app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/contacto/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contacto">> = Specific
  const handler = {} as typeof import("../../../app/contacto/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/control-accesos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/control-accesos">> = Specific
  const handler = {} as typeof import("../../../app/control-accesos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/legal/aviso-legal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/legal/aviso-legal">> = Specific
  const handler = {} as typeof import("../../../app/legal/aviso-legal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/legal/cookies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/legal/cookies">> = Specific
  const handler = {} as typeof import("../../../app/legal/cookies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/legal/privacidad/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/legal/privacidad">> = Specific
  const handler = {} as typeof import("../../../app/legal/privacidad/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/parkings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/parkings">> = Specific
  const handler = {} as typeof import("../../../app/parkings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/productos/elysium-plus/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/productos/elysium-plus">> = Specific
  const handler = {} as typeof import("../../../app/productos/elysium-plus/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/productos/elysium/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/productos/elysium">> = Specific
  const handler = {} as typeof import("../../../app/productos/elysium/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/productos/evo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/productos/evo">> = Specific
  const handler = {} as typeof import("../../../app/productos/evo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/productos/prometheus/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/productos/prometheus">> = Specific
  const handler = {} as typeof import("../../../app/productos/prometheus/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/studio/[[...tool]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/studio/[[...tool]]">> = Specific
  const handler = {} as typeof import("../../../app/studio/[[...tool]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/verifactu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verifactu">> = Specific
  const handler = {} as typeof import("../../../app/verifactu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contact">> = Specific
  const handler = {} as typeof import("../../../app/api/contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ping-google/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ping-google">> = Specific
  const handler = {} as typeof import("../../../app/api/ping-google/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/blog/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../../app/blog/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/control-accesos/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/control-accesos">> = Specific
  const handler = {} as typeof import("../../../app/control-accesos/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/legal/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/legal">> = Specific
  const handler = {} as typeof import("../../../app/legal/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/parkings/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/parkings">> = Specific
  const handler = {} as typeof import("../../../app/parkings/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/studio/[[...tool]]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/studio/[[...tool]]">> = Specific
  const handler = {} as typeof import("../../../app/studio/[[...tool]]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/verifactu/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/verifactu">> = Specific
  const handler = {} as typeof import("../../../app/verifactu/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
